version: '3.8'

services:
  # 1. The Database (PostgreSQL)
  postgres:
    image: postgres:16-alpine
    container_name: pbb_postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: product_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. The Search Engine (Meilisearch)
  meilisearch:
    image: getmeili/meilisearch:v1.10
    container_name: pbb_meili
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: masterKey123
    volumes:
      - meili_data:/meili_data

  # 3. The Cache (Redis)
  redis:
    image: redis:alpine
    container_name: pbb_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  meili_data: